{{- $fullName := include "todo.fullname" . -}}
{{- $serviceType := .Values.service.type -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  name: {{ $fullName }}-read-one
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  deployment:
    spec:
      template:
        spec:
          containers:
          - name: read-one
            env:
            - name: REDIS_HOST
              value: {{ template "todo.redis.fullname" . }}-slave
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "todo.redis.fullname" . }}
                  key: redis-password
            resources: {}
  deps: |
{{ .Files.Get "backend/package.json" | indent 4 }}
  function: |
{{ .Files.Get "backend/todos-read-one.js" | indent 4 }}
  function-content-type: text
  handler: todos.readOne
  runtime: nodejs8
  service:
    ports:
    - port: {{ $servicePort }}
      protocol: TCP
      targetPort: {{ $servicePort }}
    selector:
      app: {{ template "todo.name" . }}
      release: "{{ .Release.Name }}"
      function: {{ $fullName }}-read-one
    type: {{ $serviceType }}
