{{- $fullName := include "todo.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $fullName }}-frontend
            servicePort: 8080
        - path: /api/create
          backend:
            serviceName: {{ $fullName }}-create
            servicePort: 8080
        - path: /api/read-all
          backend:
            serviceName: {{ $fullName }}-read-all
            servicePort: 8080
        - path: /api/read
          backend:
            serviceName: {{ $fullName }}-read
            servicePort: 8080
        - path: /api/update
          backend:
            serviceName: {{ $fullName }}-update
            servicePort: 8080
        - path: /api/delete
          backend:
            serviceName: {{ $fullName }}-delete
            servicePort: 8080
