image:
  registry: docker.io
  repository: bitnami/node
  tag: 8-prod
  pullPolicy: Always

repository: https://github.com/bitnami-labs/redisdemo.git
revision: master

ingress:
  host: 192.168.99.100.nip.io

redis:
  cluster:
    enabled: true
    slaveCount: 3
