image:
  registry: docker.io
  repository: bitnami/node
  tag: 9.10.1-prod
  pullPolicy: IfNotPresent

repository: https://github.com/bitnami-labs/redisdemo.git
revision: master

ingress:
  host: 192.168.99.100.nip.io

redis:
  cluster:
    enabled: true

  master:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5

    # Redis slave Readiness Probe
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 5
