service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
  - 192.168.99.100.nip.io

redis:
  cluster:
    enabled: true

  master:
    livenessProbe:
      enabled: true
    readinessProbe:
      enabled: true
